version: "3.7"
services:
  ipfs:
    image: ipfs/go-ipfs
    ports:
      - "8080:8080"     # Gateway
      - "5001:5001"     # API and WebUI: http://0.0.0.0:5001/webui
#    volumes:
#      - foo:/bar


