# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test-job:
    runs-on: ubuntu-latest

    services:
      ipfs:
        image: ipfs/go-ipfs
        ports:
        - 5001:5001
        - 8080:8080

    steps:
    - uses: actions/checkout@v2
    - name: install emacs and test deps
      run: |
          sudo apt-get install -y emacs
          emacs --batch -l install-dependencies.el

    - name: unit tests
      run: |        
          emacs --batch -L . --eval '(progn (setq package-user-dir default-directory) (package-initialize))' -l ipfs-test  > output.txt 2>&1

    - name: integ tests
      run: |        
          emacs --batch -L . --eval '(progn (setq package-user-dir default-directory) (package-initialize))' -l ipfs-integ-test  >> output.txt 2>&1

    - name: Upload result
      uses: actions/upload-artifact@v1
      with:
        name: test output
        path: output.txt

